#### Pandas to read HTML table
##### https://pbpython.com/pandas-html-table.html

In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\rajesh\jupyter\venv\scripts\python.exe -m pip install --upgrade pip' command.


In [2]:
pip install lxml

ERROR: Could not find a version that satisfies the requirement lxml (from versions: none)
ERROR: No matching distribution found for lxml
Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd

# Test against Minnesota
# Get all tables
table_MN = pd.read_html('https://en.wikipedia.org/wiki/Minnesota')
print(f"Number of tables : {len(table_MN)}")
# Select Specific table
table_MN = pd.read_html('https://en.wikipedia.org/wiki/Minnesota', match='Election results from statewide races')
print(f"Number of tables after match: {len(table_MN)}")


# Get British Army Figures
table_list = pd.read_html('https://en.wikipedia.org/wiki/Monthly_recruiting_figures_for_the_British_Army_in_the_First_World_War')

# Will have a list of tables if more than 1 table in page
print(f"Number of tables : {len(table_list)}")

# This has only one - print it as df
df = table_list[0]
print(df)

ImportError: lxml not found, please install it

### Generate dictionary from website directly

In [27]:
import pandas as pd

import ast

# Get  table
table_events = pd.read_html('https://apscheduler.readthedocs.io/en/stable/modules/events.html#module-apscheduler.events')
print(f"Number of tables : {len(table_events)}")

df = table_events[0]

print(f"Dimensions : {df.ndim}")
print(f"Shape : {df.shape}")
print(f"Size : {df.size}")

# print('{')
# for row in df.to_numpy(dtype=object, copy=False):
#     print(f"{row[0]} : '{row[1]}',")
# print('}')

event_dict = pd.Series(df.Description.values, index=df.Constant.values).to_dict()
print(event_dict)



Number of tables : 1
Dimensions : 2
Shape : (18, 3)
Size : 54
{'EVENT_SCHEDULER_STARTED': 'The scheduler was started', 'EVENT_SCHEDULER_SHUTDOWN': 'The scheduler was shut down', 'EVENT_SCHEDULER_PAUSED': 'Job processing in the scheduler was paused', 'EVENT_SCHEDULER_RESUMED': 'Job processing in the scheduler was resumed', 'EVENT_EXECUTOR_ADDED': 'An executor was added to the scheduler', 'EVENT_EXECUTOR_REMOVED': 'An executor was removed to the scheduler', 'EVENT_JOBSTORE_ADDED': 'A job store was added to the scheduler', 'EVENT_JOBSTORE_REMOVED': 'A job store was removed from the scheduler', 'EVENT_ALL_JOBS_REMOVED': 'All jobs were removed from either all job stores or one particular job store', 'EVENT_JOB_ADDED': 'A job was added to a job store', 'EVENT_JOB_REMOVED': 'A job was removed from a job store', 'EVENT_JOB_MODIFIED': 'A job was modified from outside the scheduler', 'EVENT_JOB_SUBMITTED': 'A job was submitted to its executor to be run', 'EVENT_JOB_MAX_INSTANCES': 'A job being s

In [4]:
import pandas as pd

df = pd.DataFrame(
{'from_wbse': ['350377/TRANRL/S10187', '350377/TRANRL/S1018', '350377/TRANRL/S10187', '350377/TRANRL/S10187', '350377/TRANRL/S10187'], 
'to_wbse': ['301110/30073', '301110/30073', '301110/3007', '301110/30073', '301110/30073'], 
'hours': [11.0, 8.5, 10.5, 15.0, 11.5],
'costcentre': [7655, 7655, 7655,7655, 7655],
'activitytype': ['G05','G05','G05','G05','G05']})

# print(df)
df2=df.groupby(by=['from_wbse','to_wbse','costcentre','activitytype']).sum().reset_index()
print(df2)
# df3 = df.groupby(by=['from_wbse','to_wbse'])['hours'].sum().reset_index()
# print(df3)
# myList=df2.values.tolist()
# print(myList)
# myDictList=df2.T.to_dict().values()
# print(myDictList)
myDictList=df2.to_dict('records')
print(myDictList)

              from_wbse       to_wbse  costcentre activitytype  hours
0   350377/TRANRL/S1018  301110/30073        7655          G05    8.5
1  350377/TRANRL/S10187   301110/3007        7655          G05   10.5
2  350377/TRANRL/S10187  301110/30073        7655          G05   37.5
[{'from_wbse': '350377/TRANRL/S1018', 'to_wbse': '301110/30073', 'costcentre': 7655, 'activitytype': 'G05', 'hours': 8.5}, {'from_wbse': '350377/TRANRL/S10187', 'to_wbse': '301110/3007', 'costcentre': 7655, 'activitytype': 'G05', 'hours': 10.5}, {'from_wbse': '350377/TRANRL/S10187', 'to_wbse': '301110/30073', 'costcentre': 7655, 'activitytype': 'G05', 'hours': 37.5}]


## Dataframes
### https://realpython.com/pandas-dataframe/

### Creating a Pandas DataFrame With Dictionaries

In [30]:
import pandas as pd

# Use dictionary to pass data (can also use pandas series / list / tuple / NumPy array)
data = {
    'name':['Xavier', 'Ann', 'Jana', 'Yi', 'Robin', 'Amal', 'Nori'],
    'city' : ['Mexico City', 'Toronto', 'Prague', 'Shanghai','Manchester', 'Cairo', 'Osaka'],
    'age' : [41, 28, 33, 34, 38, 31, 37],
    'py-score' : [88.0, 79.0, 81.0, 80.0, 68.0, 61.0, 84.0]
}

row_labels = (lambda : list(range(101,114,2)))()
print(row_labels)

df = pd.DataFrame(data=data, index=row_labels)
#df=pd.DataFrame(data=data)
print(df)
print(80*'-')
print(df.head())
print(80*'-')
print(df.tail())
print(80*'-')
print(df.tail(n=2))
print(80*'-')
print(df['city'])
print(80*'-')
# print(df['101'])
print(df.age)
print(80*'-')
print(df.name[103])
import pandas as pd

# Use dictionary to pass data (can also use pandas series / list / tuple / NumPy array)
data = {
    'name':['Xavier', 'Ann', 'Jana', 'Yi', 'Robin', 'Amal', 'Nori'],
    'city' : ['Mexico City', 'Toronto', 'Prague', 'Shanghai','Manchester', 'Cairo', 'Osaka'],
    'age' : [41, 28, 33, 34, 38, 31, 37],
    'py-score' : [88.0, 79.0, 81.0, 80.0, 68.0, 61.0, 84.0]
}

row_labels = (lambda : list(range(101,114,2)))()
print(row_labels)

df = pd.DataFrame(data=data, index=row_labels)
#df=pd.DataFrame(data=data)
print(df)
print(80*'-')
print(df.head())
print(80*'-')
print(df.tail())
print(80*'-')
print(df.tail(n=2))
print(80*'-')
print(df['city'])
print(80*'-')
# print(df['101'])
print(df.age)
print(80*'-')
print(df.loc[103])
print(80*'-')
print(df.loc[103].city)

[101, 103, 105, 107, 109, 111, 113]
       name         city  age  py-score
101  Xavier  Mexico City   41      88.0
103     Ann      Toronto   28      79.0
105    Jana       Prague   33      81.0
107      Yi     Shanghai   34      80.0
109   Robin   Manchester   38      68.0
111    Amal        Cairo   31      61.0
113    Nori        Osaka   37      84.0
--------------------------------------------------------------------------------
       name         city  age  py-score
101  Xavier  Mexico City   41      88.0
103     Ann      Toronto   28      79.0
105    Jana       Prague   33      81.0
107      Yi     Shanghai   34      80.0
109   Robin   Manchester   38      68.0
--------------------------------------------------------------------------------
      name        city  age  py-score
105   Jana      Prague   33      81.0
107     Yi    Shanghai   34      80.0
109  Robin  Manchester   38      68.0
111   Amal       Cairo   31      61.0
113   Nori       Osaka   37      84.0
--------------

#### Example 2 of creating DataFrame from dictionaries

In [34]:
import pandas as pd
import numpy as np

my_dict={
    'x': [1,2,3],
    'y': np.array([2,4,8]),
    'z': 100
}

df = pd.DataFrame(data=my_dict)
print(df)
print(80*'-')
df = pd.DataFrame(my_dict, index=[101,103,105], columns=['z','x','y'])
print(df)
print(80*'-')                                                        

   x  y    z
0  1  2  100
1  2  4  100
2  3  8  100
--------------------------------------------------------------------------------
       z  x  y
101  100  1  2
103  100  2  4
105  100  3  8
--------------------------------------------------------------------------------


### Creating a Pandas DataFrame With Lists

####  list of dictionaries to create a Pandas DataFrame

In [35]:
my_list=[
    {'x': 1 , 'y' : 2 , 'z': 3},
    {'x': 2 , 'y' : 4 , 'z': 6},
    {'x': 3 , 'y' : 6 , 'z': 8},
]

df = pd.DataFrame(my_list)
print(df)

   x  y  z
0  1  2  3
1  2  4  6
2  3  6  8


####  nested list to create a Pandas DataFrame

In [38]:
my_list=[
    [1,2,3],
    [2,4,6],
    [3,6,8]
]

df = pd.DataFrame(my_list)
print(df)
print(80*'-')
df = pd.DataFrame(data=my_list, index=('a','b','c'), columns=('x','y','z'))
print(df)

   0  1  2
0  1  2  3
1  2  4  6
2  3  6  8
--------------------------------------------------------------------------------
   x  y  z
a  1  2  3
b  2  4  6
c  3  6  8


### Creating a Pandas DataFrame With NumPy Arrays

In [47]:
my_array = np.array([
    [1,2,3],
    [2,4,6],
    [3,6,8]
])
print(my_array)
print('-'*80)
df = pd.DataFrame(my_array, copy=False)
print(df)
print('-'*80)
'''
When copy is set to False (its default setting), 
the data from the NumPy array isn’t copied. 
This means that the original data from the array is assigned to the Pandas DataFrame. 
If you modify the array, then your DataFrame will change too
'''
my_array[0,0] = 1000
print(my_array)
print(df)
print('-'*80)

df = pd.DataFrame(my_array, copy=True)
print(my_array)
print(df)
print('-'*80)

my_array[0,1] = 1000
print(my_array)
print(df)
print('-'*80)

[[1 2 3]
 [2 4 6]
 [3 6 8]]
--------------------------------------------------------------------------------
   0  1  2
0  1  2  3
1  2  4  6
2  3  6  8
--------------------------------------------------------------------------------
[[1000    2    3]
 [   2    4    6]
 [   3    6    8]]
      0  1  2
0  1000  2  3
1     2  4  6
2     3  6  8
--------------------------------------------------------------------------------
[[1000    2    3]
 [   2    4    6]
 [   3    6    8]]
      0  1  2
0  1000  2  3
1     2  4  6
2     3  6  8
--------------------------------------------------------------------------------
[[1000 1000    3]
 [   2    4    6]
 [   3    6    8]]
      0  1  2
0  1000  2  3
1     2  4  6
2     3  6  8
--------------------------------------------------------------------------------


### Creating a Pandas DataFrame From Files

In [48]:
pd.read_csv('data\pandas_csv_example.csv')

Unnamed: 0    name         city  age  py-score
0         101  Xavier  Mexico City   41      88.0
1         102     Ann      Toronto   28      79.0
2         103    Jana       Prague   33      81.0
3         104      Yi     Shanghai   34      80.0
4         105   Robin   Manchester   38      68.0
5         106    Amal        Cairo   31      61.0
6         107    Nori        Osaka   37      84.0

### Retrieving Labels and Data

#### Index using arange

In [61]:
import numpy as np

df = pd.read_csv('data\pandas_csv_example.csv')

print(df.columns)
print(df.columns[1])
print(70*'^')
print(df.index)
df.index = np.arange(start=100, stop=114, step=2, dtype=float)
print(df.index)
df.index = np.arange(start=100, stop=114, step=2, dtype=int)
print(df.index)


Index(['Unnamed: 0', 'name', 'city', 'age', 'py-score'], dtype='object')
name
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RangeIndex(start=0, stop=7, step=1)
Float64Index([100.0, 102.0, 104.0, 106.0, 108.0, 110.0, 112.0], dtype='float64')
Int64Index([100, 102, 104, 106, 108, 110, 112], dtype='int64')


#### extract data from a Pandas DataFrame without its labels using numpy

In [65]:
import numpy as np

df = pd.read_csv('data\pandas_csv_example.csv')
print(df)
print('-'*70)
print(df.to_numpy(dtype=object, copy=False))
print('-'*70)
print(df.values)


   Unnamed: 0    name         city  age  py-score
0         101  Xavier  Mexico City   41      88.0
1         102     Ann      Toronto   28      79.0
2         103    Jana       Prague   33      81.0
3         104      Yi     Shanghai   34      80.0
4         105   Robin   Manchester   38      68.0
5         106    Amal        Cairo   31      61.0
6         107    Nori        Osaka   37      84.0
----------------------------------------------------------------------
[[101 'Xavier' 'Mexico City' 41 88.0]
 [102 'Ann' 'Toronto' 28 79.0]
 [103 'Jana' 'Prague' 33 81.0]
 [104 'Yi' 'Shanghai' 34 80.0]
 [105 'Robin' 'Manchester' 38 68.0]
 [106 'Amal' 'Cairo' 31 61.0]
 [107 'Nori' 'Osaka' 37 84.0]]
----------------------------------------------------------------------
[[101 'Xavier' 'Mexico City' 41 88.0]
 [102 'Ann' 'Toronto' 28 79.0]
 [103 'Jana' 'Prague' 33 81.0]
 [104 'Yi' 'Shanghai' 34 80.0]
 [105 'Robin' 'Manchester' 38 68.0]
 [106 'Amal' 'Cairo' 31 61.0]
 [107 'Nori' 'Osaka' 37 84.0]]


#### control dtypes using numpy

In [70]:
import numpy as np

df = pd.read_csv('data\pandas_csv_example.csv')
print(df)
print('-'*70)

print(df.dtypes)
print('-'*70)

df_ = df.astype({'age':np.float64 , 'py-score':np.int32})
print(df_)
print(df_.dtypes)
print('-'*70)


   Unnamed: 0    name         city  age  py-score
0         101  Xavier  Mexico City   41      88.0
1         102     Ann      Toronto   28      79.0
2         103    Jana       Prague   33      81.0
3         104      Yi     Shanghai   34      80.0
4         105   Robin   Manchester   38      68.0
5         106    Amal        Cairo   31      61.0
6         107    Nori        Osaka   37      84.0
----------------------------------------------------------------------
Unnamed: 0      int64
name           object
city           object
age             int64
py-score      float64
dtype: object
----------------------------------------------------------------------
   Unnamed: 0    name         city   age  py-score
0         101  Xavier  Mexico City  41.0        88
1         102     Ann      Toronto  28.0        79
2         103    Jana       Prague  33.0        81
3         104      Yi     Shanghai  34.0        80
4         105   Robin   Manchester  38.0        68
5         106    Amal       

#### Dimensions of Dataframe

In [74]:
import numpy as np

df = pd.read_csv('data\pandas_csv_example.csv')
print(df)
print('-'*70)
print(f"Dimensions : {df.ndim}")
print(f"Shape : {df.shape}")
print(f"Size : {df.size}")
print(f"Memory Usage : {df.memory_usage()}")
print('-'*70)


   Unnamed: 0    name         city  age  py-score
0         101  Xavier  Mexico City   41      88.0
1         102     Ann      Toronto   28      79.0
2         103    Jana       Prague   33      81.0
3         104      Yi     Shanghai   34      80.0
4         105   Robin   Manchester   38      68.0
5         106    Amal        Cairo   31      61.0
6         107    Nori        Osaka   37      84.0
----------------------------------------------------------------------
Dimensions : 2
Shape : (7, 5)
Size : 35
Memory Usage : Index         128
Unnamed: 0     56
name           56
city           56
age            56
py-score       56
dtype: int64
----------------------------------------------------------------------


### Accessing and Modifying Data

In [92]:
df = pd.read_csv('data\pandas_csv_example.csv')
print(df)
print('-'*70)
df.index = np.arange(start=100, stop=107, step=1, dtype=int)
print(df)
print('-'*70)
print(df.loc[100])
print('-'*70)
print(df.iloc[0])
print('-'*70)
print(df.at[100,'name'])
print('-'*70)
print(df.iat[0,1])
print('-'*70)
print(df['name'])

   Unnamed: 0    name         city  age  py-score
0         101  Xavier  Mexico City   41      88.0
1         102     Ann      Toronto   28      79.0
2         103    Jana       Prague   33      81.0
3         104      Yi     Shanghai   34      80.0
4         105   Robin   Manchester   38      68.0
5         106    Amal        Cairo   31      61.0
6         107    Nori        Osaka   37      84.0
----------------------------------------------------------------------
     Unnamed: 0    name         city  age  py-score
100         101  Xavier  Mexico City   41      88.0
101         102     Ann      Toronto   28      79.0
102         103    Jana       Prague   33      81.0
103         104      Yi     Shanghai   34      80.0
104         105   Robin   Manchester   38      68.0
105         106    Amal        Cairo   31      61.0
106         107    Nori        Osaka   37      84.0
----------------------------------------------------------------------
Unnamed: 0            101
name            

### Slicing using loc and iloc

In [118]:
print(df.loc[100])
print('-'*70)
print(df.loc[100,'city'])
print('-'*70)
print(df.loc[:,'city'])
print('-'*70)
print(df['city'])
print('-'*70)
print(df.loc[101:105,'city'])
print('-'*70)
print(df.iloc[:,1])
print('-'*70)
print(df.iloc[2:5,3])
print('-'*70)
print(df.iloc[2:7:2,2])
print('-'*70)
print(df.iloc[slice(2,7,2), 2])
print('-'*70)
print(df.iloc[np.s_[2:7:2], 2])
print('-'*70)
print(df.iloc[pd.IndexSlice[2:7:2], 2])

Unnamed: 0            101
name               Xavier
city          Mexico City
age                    41
py-score             88.0
Name: 100, dtype: object
----------------------------------------------------------------------
Mexico City
----------------------------------------------------------------------
100    Mexico City
101        Toronto
102         Prague
103       Shanghai
104     Manchester
105          Cairo
106          Osaka
Name: city, dtype: object
----------------------------------------------------------------------
100    Mexico City
101        Toronto
102         Prague
103       Shanghai
104     Manchester
105          Cairo
106          Osaka
Name: city, dtype: object
----------------------------------------------------------------------
101       Toronto
102        Prague
103      Shanghai
104    Manchester
105         Cairo
Name: city, dtype: object
----------------------------------------------------------------------
100    Xavier
101       Ann
102      Jana
10

### Get value of cell at loc

In [126]:
print(df)
print(df.at[102, 'name'])
print(df.iat[2,1])

     Unnamed: 0    name         city  age  py-score
100         101  Xavier  Mexico City   41      88.0
101         102     Ann      Toronto   28      79.0
102         103    Jana       Prague   33      81.0
103         104      Yi     Shanghai   34      80.0
104         105   Robin   Manchester   38      68.0
105         106    Amal        Cairo   31      61.0
106         107    Nori        Osaka   37      84.0
Jana
Jana


### setting data with accessors

In [135]:
print(df.loc[:, 'py-score'])
print('.'*100)
df.loc[100:102,'py-score'] = [0,0,0]
print(df.loc[:, 'py-score'])

df.drop(100102,axis=0)

100        0.0
101        0.0
102        0.0
103       80.0
104       68.0
105       61.0
106       84.0
100102     NaN
Name: py-score, dtype: float64
....................................................................................................
100        0.0
101        0.0
102        0.0
103       80.0
104       68.0
105       61.0
106       84.0
100102     NaN
Name: py-score, dtype: float64


Unnamed: 0    name         city   age  py-score
100       101.0  Xavier  Mexico City  41.0       0.0
101       102.0     Ann      Toronto  28.0       0.0
102       103.0    Jana       Prague  33.0       0.0
103       104.0      Yi     Shanghai  34.0      80.0
104       105.0   Robin   Manchester  38.0      68.0
105       106.0    Amal        Cairo  31.0      61.0
106       107.0    Nori        Osaka  37.0      84.0

### Inserting & deleting data

In [149]:
gas_df_dict={
    'name':['Helium','Neon','Krypton','Xenon'],
    'number' : [2,10,36,54]
}
gas_df = pd.DataFrame(data=gas_df_dict)
print(gas_df)
# create Series object to insert
new_gas=pd.Series(data=['Radon',86],index=gas_df.columns, name = 4)
print(new_gas)
# insert
gas_df.append(new_gas)
print(gas_df)
gas_df = gas_df.append(new_gas)
print(gas_df)
# Create dummy gas & drop
new_gas = pd.Series(data=['Dummy',1200], index=gas_df.columns,name=1200)
gas_df = gas_df.append(new_gas)
print(gas_df)
gas_df.drop(labels=[1200],inplace=True)
print(gas_df)

      name  number
0   Helium       2
1     Neon      10
2  Krypton      36
3    Xenon      54
name      Radon
number       86
Name: 4, dtype: object
      name  number
0   Helium       2
1     Neon      10
2  Krypton      36
3    Xenon      54
      name  number
0   Helium       2
1     Neon      10
2  Krypton      36
3    Xenon      54
4    Radon      86
         name  number
0      Helium       2
1        Neon      10
2     Krypton      36
3       Xenon      54
4       Radon      86
1200    Dummy    1200
      name  number
0   Helium       2
1     Neon      10
2  Krypton      36
3    Xenon      54
4    Radon      86


In [160]:
gas_df_dict={
    'name':['Helium','Neon','Krypton','Xenon'],
    'number' : [2,10,36,54]
}
gas_df = pd.DataFrame(data=gas_df_dict)
print(gas_df)
gas_df['dummy'] = (lambda: list(range(100,104)))()
print(gas_df)
gas_df['dummy2'] = 10
print(gas_df)
gas_df.insert(loc=3, column='weight', value = np.array([4.0026 , 20.180, 83.798, 131.29]))
print(gas_df)
gas_df.drop(labels=['dummy','dummy2'], axis=1)
print(gas_df)
gas_df.drop(labels=['dummy','dummy2'], axis=1, inplace=True)
print(gas_df)

      name  number
0   Helium       2
1     Neon      10
2  Krypton      36
3    Xenon      54
      name  number  dummy
0   Helium       2    100
1     Neon      10    101
2  Krypton      36    102
3    Xenon      54    103
      name  number  dummy  dummy2
0   Helium       2    100      10
1     Neon      10    101      10
2  Krypton      36    102      10
3    Xenon      54    103      10
      name  number  dummy    weight  dummy2
0   Helium       2    100    4.0026      10
1     Neon      10    101   20.1800      10
2  Krypton      36    102   83.7980      10
3    Xenon      54    103  131.2900      10
      name  number  dummy    weight  dummy2
0   Helium       2    100    4.0026      10
1     Neon      10    101   20.1800      10
2  Krypton      36    102   83.7980      10
3    Xenon      54    103  131.2900      10
      name  number    weight
0   Helium       2    4.0026
1     Neon      10   20.1800
2  Krypton      36   83.7980
3    Xenon      54  131.2900


### Concat

In [30]:
import pandas as pd

city_countries = pd.DataFrame({
    "country":["Holland", "Japan", "Holland", "Canada", "Spain"],
    "capital":[1,1,0,0,0],
    "city" : ["Amsterdam", "Tokyo", "Rotterdam", "Toronto", "Barcelona"]
})

## TBD